name: Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.9.1
      with:
        args: --verbose --no-progress --accept 200,203,429 './**/*.md'
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Comment on PR
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Link Checker Failed**\n\nSome links in your changes appear to be broken. Please check the logs above and fix any broken links before merging.'
          })